# Generated by Django 3.1 on 2020-08-22 21:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Заголовок')),
                ('details', models.TextField(verbose_name='Детали')),
                ('start_time', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата начала')),
                ('accepts', models.BigIntegerField(default=0, verbose_name='За')),
                ('de_accepts', models.BigIntegerField(default=0, verbose_name='Против')),
                ('start_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
