# Generated by Django 3.1 on 2020-08-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='canvote',
            field=models.BooleanField(default=True, verbose_name='can vote'),
        ),
    ]
