# Generated by Django 3.1 on 2020-08-23 00:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0002_vote_canvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='voters',
            field=models.ManyToManyField(default=[models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)], related_name='vaters', to=settings.AUTH_USER_MODEL),
        ),
    ]
